# Generated by Django 3.0.6 on 2020-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('director', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=8)),
                ('genre', models.CharField(choices=[('none', 'بدون دسته بندی'), ('action', 'اکشن'), ('historical', 'تاریخی'), ('horror', 'ترسناک'), ('crime', 'جنایی'), ('war', 'جنگی'), ('family', 'خانوادگی'), ('news', 'خبری'), ('drama', 'درام'), ('mysterious', 'راز آلود'), ('biography', 'زندگی نامه'), ('science_fiction', 'علمی-تخیلی'), ('fantasy', 'فانتزی'), ('comedy', 'کمدی'), ('short', 'کوتاه'), ('adventure', 'ماجراجویی'), ('documentary', 'مستند'), ('musical', 'موزیکال'), ('thriller', 'هیجان انگیز'), ('sport', 'ورزشی'), ('western', 'وسترن')], default='بدون دسته بندی', max_length=20)),
                ('rank', models.FloatField(default=0)),
                ('summary', models.CharField(max_length=200)),
                ('cover', models.ImageField(null=True, upload_to='files/11ab1e12ae8017317b9e679802e560e091cfcafe10b2e95e6d10fc67ad415db1')),
            ],
        ),
    ]
