# Generated by Django 3.0.6 on 2020-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(null=True, upload_to='files/<django.db.models.fields.CharField>-<django.db.models.fields.DateField>'),
        ),
    ]
