# Generated by Django 3.0.6 on 2020-05-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200515_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(null=True, upload_to='files/<django.db.models.fields.CharField>-'),
        ),
    ]
